baseURL = 'https://tricky-tactics.github.io/Homepage'
languageCode = 'en-us'
title = 'TrickyTactics'

[build]
  [build.postCSS]
    includeFiles = "assets/css/*.css"
    excludeFiles = "assets/css/ignore-*.css"
